---
title: "TidyTemplate"
date: 2020-09-10
output: html_output
editor_options: 
  chunk_output_type: console
---

# TidyTuesday - Coffe Ratings - 2020-07-07

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE, message = FALSE,
                      dpi = 180, fig.width = 8, fig.height = 5)

library(tidyverse)
library(tidytuesdayR)
library(scales)
library(broom)  
theme_set(theme_light())
```

# Load the weekly Data

Download the weekly data and make available in the `tt` object.

```{r Load}

tt <- tt_load("2020-07-07")
```

# Read the files
```{r}
coffee_rating <- tt$coffee_ratings

coffee_rating <- coffee_rating %>% 
    filter(total_cup_points != 0)
```

```{r}
coffee_rating %>%
  ggplot(aes(cupper_points)) +
  geom_histogram()
```

```{r}
coffee_rating %>% 
  filter(country_of_origin == "Ethiopia") %>% 
  select(owner, country_of_origin, species, aroma:moisture) %>% 
  pivot_longer(aroma:moisture, names_to = "characterstic", values_to = "value") %>% 
  mutate(characterstic = str_to_title(characterstic)) %>%
  group_by(characterstic) %>% 
  summarise(mean_value = mean(value)) %>% 
  ggplot(aes(fct_reorder(characterstic, mean_value), mean_value)) +
  geom_col(aes(fill = characterstic), show.legend = F) +
  coord_flip()
```

```{r}
coffee_rating %>% 
#  filter(country_of_origin == "Ethiopia") %>% 
  select(cupper_points, aroma:moisture) %>% 
  pivot_longer(aroma:moisture, names_to = "characterstic", values_to = "value") %>% 
  ggplot(aes(value, cupper_points)) +
  geom_point() +
  facet_wrap(~characterstic, scales = "free")
```

```{r}
coffee_rating %>% 
  select(cupper_points, altitude_low_meters:altitude_mean_meters) %>% 
  pivot_longer(altitude_low_meters:altitude_mean_meters, names_to = "altitude", values_to = "value") %>% 
  ggplot(aes(value, cupper_points)) +
  geom_point() +
  facet_wrap(~altitude, scales = "free")
```

```{r}
coffee_rating %>% 
  count(country_of_origin, company, sort = T) %>% 
    drop_na() %>% 
  head(10) %>% 
  knitr::kable()
```

```{r t test on coffee species}
coffee_rating %>% 
  select(species, aroma:moisture) %>%
  pivot_longer(aroma:moisture, names_to = "characterstic", values_to = "value", values_drop_na = T) %>% 
  nest(datagroup = c(species, value)) %>% 
  mutate(t_test = map(datagroup, ~t.test(value~species, data = .)),
         tidied = map(t_test, tidy)) %>% 
  unnest(tidied) %>% 
  ggplot(aes(characterstic, estimate, color = characterstic)) +
  geom_point() +
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high)) + 
  geom_hline(yintercept = 0, linetype = "dashed") +
  coord_flip() +
  theme(legend.position = "none") +
  labs(title = "Does species type make any impact on characterstic")

```

```{r}
coffee_rating %>% 
  select(species, aroma:moisture) %>%
  pivot_longer(aroma:moisture, names_to = "characterstic", values_to = "value", values_drop_na = T) %>% 
  nest(datagroup = c(species, value)) %>% 
  mutate(t_test = map(datagroup, ~t.test(value~species, data = .)),
         tidied = map(t_test, tidy)) %>% 
  unnest(tidied) %>% 
  ggplot(aes(p.value, characterstic)) +
  geom_point() +
  geom_vline(xintercept = 0, linetype = "dashed")

```

